[package]
name = "finder"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bitvec = "1.0.1"

[dependencies.windows]
version = "0.59.0"
features = ["Win32_Storage_FileSystem"]
